### ISSUE TITLE
Suggestion: Use YouTube's inbuilt colour variables for automatically matching the theme

### ISSUE THREAD

**Issue by CeaneC** [z0ccc/Reddit-Wherever#1]
To save the need for having a dark mode option, you could instead use YouTube's built in colour variables. (E.g. `--yt-spec-text-primary` is #0A0A0A when in light mode, and #FFF when in dark mode.) That way your additions will automatically match the theme that the user has set up

I don't think Google has an official list anywhere, so my three best suggestions for finding the full list of variables would be:
1. Using inspect element to set something's colour to `var(--yt)` and see what's in the autocomplete options
2. Have a look through this site, which seems to have compiled them: https://codepen.io/nandes2062/pen/RmNEMr
3. Dig through the sources to try and find the CSS definitions yourself

Thanks for setting up the extension though! I've missed having AlienTube/SnooTube since they stopped working

EDIT: I just realised this extension is designed for working on any page, not just YouTube - so as an alternative, could I suggest automatically setting the dark mode option based on the browser's theme?

**Comment by z0ccc** [comment]
I will definitely look into automatically setting the dark mode option based on the browser's theme. Thanks

**Comment by z0ccc** [comment]
This feature has been implemented and will be in production soon.

**Comment by FoxxMD** [comment]
I see this was implemented in 67c5534d1c30cc8546b5b89a2a2d1ab3f06a9141 but it's still not working for me. On Ubuntu 20.04 using either GTK+ (dark theme) or Just Black (Classic Chrome theme) AND dark mode for youtube the comments are still using dark text.

**Comment by z0ccc** [comment]
I will look into it.

**Comment by FoxxMD** [comment]
Also want to add that dark mode text works correctly on OSX -- it must be specific to GTK or linux/ubuntu.

**Comment by z0ccc** [comment]
I have added user options to toggle the theme if the extension did not properly initialize to the system settings.  It will be in production as soon as google approves the update.

**Comment by FoxxMD** [comment]
thank you!
