### ISSUE TITLE
not work as well in Brave with Shields ON in YouTube

### ISSUE THREAD

**Issue by salehif** [z0ccc/Reddit-Wherever#10]
Hi

I tried it with Brave browser and it's work fine

but inside YouTube pages doesn't shows (as Comments) until I turn off shields ( trackers & ads )

I hope there is a fix for that

thanks after all

**Comment by z0ccc** [comment]
It works fine for me even when I have Trackers & ads blocking set to 'aggressive'. Is this issue still happening for you?

**Comment by salehif** [comment]
Yes now is fixed in version 2.1.0
