### ISSUE TITLE
YT weird icons on clicking/ holding 

### ISSUE THREAD

**Issue by Dschogo** [z0ccc/Reddit-Wherever#12]
As described in the title these strange icons appear uppon clicking and holding various items. (Videos, menus almost everxthing)
Its not really breaking, everything still works and its gone after releasing the mouse button.

Is there something planned with these icons? Cant figure out how to interact with them if its even possible.

Screen:
![image](https://user-images.githubusercontent.com/36862419/130936305-2d6b9a15-0d3d-4124-9a3b-435549f206dd.png)

**Comment by z0ccc** [comment]
Google has finally approved the update. Issue is fixed.
