### ISSUE TITLE
Support Invidious

### ISSUE THREAD

**Issue by Victor239** [z0ccc/Reddit-Wherever#14]
[Invidious](https://github.com/iv-org/invidious) is a very popular privacy-enhancing web frontend for YouTube ([example instance here](https://invidious.kavin.rocks/)). It would be great to have the Reddit comments on the original YouTube videos show up on Invidious instances too.

**Comment by z0ccc** [comment]
I don't think I will have the time to implement this. But I encourage you to give it a try!

**Comment by Victor239** [comment]
Shouldn't this issue be kept open then for another contributor to do it then?
