### ISSUE TITLE
"Sort By" inaccessible on lower resolution

### ISSUE THREAD

**Issue by ManolisPapd** [z0ccc/Reddit-Wherever#15]
When the extension is presenting the YouTube comments and the browser resolution is lower (haven't tested the exact number) the "Sort By" functionality isn't available.

**Comment by z0ccc** [comment]
I don't understand what you mean? Can you provide a screenshot? Thanks

**Comment by ManolisPapd** [comment]
"Sort By" isn't clickable when the resolution of the browser is lower than 1000px as mentioned on the PR #16.
The cause is the media query, that is being activated under 1000px.

![image](https://user-images.githubusercontent.com/10334230/132135670-8e50880d-e991-4eb1-9d3c-edf12871639c.png)

**Comment by z0ccc** [comment]
This will be in the next version.
