### ISSUE TITLE
home page reddit.com top result is very not cool

### ISSUE THREAD

**Issue by mataski** [z0ccc/Reddit-Wherever#17]
Debug: go to reddit.com and click the icon of this addon...

Firefox addon.

**Comment by z0ccc** [comment]
It looks fine to me. What's wrong?

**Comment by mataski** [comment]
![image](https://user-images.githubusercontent.com/62036912/132132171-10011032-9ba1-4bed-8f74-89609a56b21b.png)

**Comment by z0ccc** [comment]
That's not what mine looks like 
![image](https://user-images.githubusercontent.com/70310180/132132280-ead96f1d-b062-4230-8836-52f591ed2432.png)

Can you send me a link to the post?

**Comment by mataski** [comment]
https://www.reddit.com/r/Kanye/comments/4cw358/niggers/ it does link to homepage. Still, it should be censored or something. I don't think users installing the addon will be happy to see this as first thing when clicked.

I get this on Firefox logged in/logged out and on private/incognito mode.

**Comment by z0ccc** [comment]
hmm ill look into issue. It weird that I'm not seeing it. I will try to fix it.
