### ISSUE TITLE
Suggestion: add a YouTube tab on the left of all subreddit tabs to display original YouTube comments

### ISSUE THREAD

**Issue by bmrejen** [z0ccc/Reddit-Wherever#2]
![Untitled](https://user-images.githubusercontent.com/20118433/119351892-4e0a8180-bca1-11eb-8cde-34df5c7b8395.png)

**Comment by bmrejen** [comment]
I have been considering uninstalling because I can't easily display original comments

**Comment by z0ccc** [comment]
You can toggle between the Reddit and YouTube comments by clicking the icon in the top right.

![image](https://user-images.githubusercontent.com/70310180/119380506-d0d61100-bc8e-11eb-8b23-7a0db513597e.png)
![image](https://user-images.githubusercontent.com/70310180/119380552-e1868700-bc8e-11eb-9ae4-43cef3d6a86a.png)
