### ISSUE TITLE
Color of text, not working propely on Youtube Dark Mode, Chrome Browser

### ISSUE THREAD

**Issue by IamTregsthedev** [z0ccc/Reddit-Wherever#3]
The text doesn't show on Youtube Darkmode. 

Here's a video for example: https://www.youtube.com/watch?v=lx-__lBS6a4

![image](https://user-images.githubusercontent.com/21000033/121292362-d4d17800-c8b7-11eb-8efe-b029232b0458.png)

**Comment by z0ccc** [comment]
There's an option to change to dark mode. You can get to the options page by right clicking the icon and selecting 'Options'.
