### ISSUE TITLE
Possible Firefox version in the works?

### ISSUE THREAD

**Issue by CKraft11** [z0ccc/Reddit-Wherever#5]
I know me and many others would love a Firefox version of this. Would this be possible to implement?

**Comment by z0ccc** [comment]
This extension uses manifest v3 which is not supported by Firefox. It's still possible but it would require some customization. I do plan to convert it over at some point in the future but I just don't have much time to spare right now.

**Comment by ayunami2000** [comment]
The `!remind me 15 days` thing went off from reddit regarding this. Just letting you know. No rush personally but others might want it more than I do.

**Comment by mwaitzman** [comment]
yes

**Comment by z0ccc** [comment]
The Firefox version can be downloaded here https://addons.mozilla.org/en-CA/firefox/addon/reddit-wherever/

**Comment by plantman1** [comment]
Finally. You said it would take 15 days. Disappointing that you can't follow a schedule...
