### ISSUE TITLE
Increase text contrast (Dark theme)

### ISSUE THREAD

**Issue by jac0b-w** [z0ccc/Reddit-Wherever#6]
![image](https://user-images.githubusercontent.com/51512690/124001682-cb29c480-d9cc-11eb-86e0-05021edc8689.png)

I find the grey text on a grey background a little hard to read especially for a large block of text. I think that white text would be more appropriate as it is easier to read and fits in with youtube's dark theme which also has white text.

**Comment by z0ccc** [comment]
I have increased the text contrast for the dark theme. It will be in production as soon as google approves the update.
